[general]
Name = "J0002+6216" # Pulsar Name
P = 0.11536356826797663 # Rotation period in s
B12 = 0.8296855859858439 # Magnetic filed on the polar cap, nomralized to 1e12 G
chi = 45 # inclination angle in degrees

[mechanics]
Rs = 12 # Neutron star radius in km
M = 1.4 # Neutron star mass in solar masses
Ir = 100 # Neutron star moment of inertia in Solar masses * km^2
